---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:latest"
  amd64: "ghcr.io/home-assistant/amd64-base-python:latest"
  armhf: "ghcr.io/home-assistant/armhf-base-python:latest"
  armv7: "ghcr.io/home-assistant/armv7-base-python:latest"
  i386: "ghcr.io/home-assistant/i386-base-python:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Cumulus"
  org.opencontainers.image.description: "Client for TeepCo Cumulus Cloud"
  org.opencontainers.image.source: "https://github.com/teepco/ha-addons"
  org.opencontainers.image.licenses: "MIT"
